# -*- coding: utf-8 -*-
"""yash Dataframes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vTpOuTc3A5Rk2Rxx5Cx6wsdYB8VUgCHa
"""

pip install pandas

import pandas as pd
data = {
      'Product': ['Laptop', 'Phone', 'Tablet'],
      'Price': [1200, 800, 400],
      'Stock': [10, 50, 30]
  }
df = pd.DataFrame(data)
print(df)

print(df['Product'])

df['Discount'] =  [100,50,20]
print(df)

df = df.drop('Stock', axis=1)

print(df)

print(df.iloc[1])

filtered_df = df[df['Price'] >500]
print(filtered_df)

data = [
      ['Alice', 24, 'Engineer'],
      ['Bob', 30, 'Doctor'],
      ['Charlie', 22, 'Artist']
]
columns = ['Name', 'Age', 'Occupation']
df = pd.DataFrame(data, columns=columns)
print(df)

df['Salary'] = [70000,80000,50000]
df['Experience'] = [2,5,1]
print(df)

filtered_df = df[(df['Age'] > 25) & (df['Occupation'] == 'Doctor')]
print(filtered_df)

df['Salary'] = df['Salary'] * 1.10
print(df)